services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: go_app
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: myuser
      DB_PASSWORD: mypassword
      DB_NAME: mydatabase
    ports:
      - "8888:8888"
    networks:
      - app-network